version: '3.7'
services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB: cmdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=cmdb2023!
    ports:
      - '5432:5432'
